package com.projectapp.tempus.ui.ai.compose

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * AI-NATIVE UI DESIGN SYSTEM - Premium Chat Interface
 * Style: Modern, conversational, minimal chrome, streaming text animations
 * Generated by: ui-ux-pro-max workflow
 * ═══════════════════════════════════════════════════════════════════════════════
 */

/**
 * Premium AI Chat Color Palette
 * Style: AI-Native UI with Purple/Cyan accents - Light Mode
 */
object ChatColors {
    // ═══ PRIMARY PALETTE - Deep Purple Gradient ═══
    val Primary = Color(0xFF7C3AED)         // Violet 600
    val PrimaryLight = Color(0xFFA78BFA)    // Violet 400
    val PrimaryDark = Color(0xFF5B21B6)     // Violet 800
    
    // ═══ ACCENT - Cyan/Turquoise ═══
    val Accent = Color(0xFF06B6D4)          // Cyan 500
    val AccentLight = Color(0xFF22D3EE)     // Cyan 400
    val AccentGlow = Color(0xFF67E8F9)      // Cyan 300
    val OnAccent = Color(0xFFFFFFFF)
    
    // ═══ LIGHT MODE BACKGROUND ═══
    val Background = Color(0xFFF8FAFC)      // Slate 50
    val BackgroundGradientStart = Color(0xFFFFFFFF)
    val BackgroundGradientEnd = Color(0xFFF1F5F9)
    val Surface = Color(0xFFFFFFFF)         // White
    val SurfaceVariant = Color(0xFFF1F5F9)  // Slate 100
    val SurfaceGlass = Color(0xFF0F172A).copy(alpha = 0.03f)
    val BorderGlass = Color(0xFF0F172A).copy(alpha = 0.08f)
    
    // ═══ TEXT COLORS ═══
    val TextPrimary = Color(0xFF0F172A)     // Slate 900
    val TextSecondary = Color(0xFF475569)   // Slate 600
    val TextMuted = Color(0xFF94A3B8)       // Slate 400
    val TextDim = Color(0xFFCBD5E1)         // Slate 300
    
    // ═══ CHAT BUBBLES ═══
    val UserBubble = Color(0xFF7C3AED)      // Violet gradient start
    val UserBubbleEnd = Color(0xFF8B5CF6)   // Violet gradient end
    val UserBubbleText = Color(0xFFFFFFFF)
    
    val AIBubble = Color(0xFFF1F5F9)        // Slate 100
    val AIBubbleLight = Color(0xFFF8FAFC)   // Slate 50
    val AIBubbleText = Color(0xFF0F172A)    // Slate 900
    val AIBubbleBorder = Color(0xFF0F172A).copy(alpha = 0.06f)
    
    // ═══ STATUS INDICATORS ═══
    val Online = Color(0xFF10B981)          // Emerald 500
    val OnlineGlow = Color(0xFF34D399)      // Emerald 400
    val Typing = Color(0xFF06B6D4)          // Cyan 500 - AI thinking
    val TypingGlow = Color(0xFF22D3EE)      // Cyan 400
    val Error = Color(0xFFEF4444)           // Red 500
    val Success = Color(0xFF22C55E)         // Green 500
    
    // ═══ SPECIAL EFFECTS ═══
    val GlowPurple = Color(0xFF7C3AED).copy(alpha = 0.15f)
    val GlowCyan = Color(0xFF06B6D4).copy(alpha = 0.15f)
    val Shimmer = Color(0xFF0F172A).copy(alpha = 0.05f)
    
    // ═══ INPUT FIELD ═══
    val InputBackground = Color(0xFFF1F5F9) // Slate 100
    val InputBorder = Color(0xFFE2E8F0)     // Slate 200
    val InputBorderFocused = Color(0xFF7C3AED)
    val InputPlaceholder = Color(0xFF94A3B8) // Slate 400
    
    // ═══ MODE TOGGLE ═══
    val ModeActive = Color(0xFF7C3AED)
    val ModeInactive = Color(0xFFE2E8F0)    // Slate 200
    val ModeText = Color(0xFFFFFFFF)
    val ModeTextInactive = Color(0xFF64748B) // Slate 500
}

/**
 * Chat dimensions and spacing
 */
object ChatDimens {
    val BubbleCornerRadius = 20.dp
    val BubbleSmallCorner = 6.dp
    val BubblePadding = 14.dp
    val BubblePaddingHorizontal = 16.dp
    val MessageSpacing = 12.dp
    val AvatarSize = 40.dp
    val AvatarSizeSmall = 32.dp
    val InputHeight = 52.dp
    val InputCornerRadius = 26.dp
    val SendButtonSize = 44.dp
    val TopBarHeight = 72.dp
    val ModeToggleHeight = 40.dp
}

/**
 * Light color scheme for Chat
 */
val ChatLightColorScheme = lightColorScheme(
    primary = ChatColors.Primary,
    onPrimary = Color.White,
    secondary = ChatColors.Accent,
    onSecondary = Color.White,
    tertiary = ChatColors.PrimaryLight,
    background = Color(0xFFF8FAFC),
    onBackground = Color(0xFF0F172A),
    surface = Color.White,
    onSurface = Color(0xFF0F172A),
    surfaceVariant = Color(0xFFF1F5F9),
    onSurfaceVariant = Color(0xFF475569),
    error = ChatColors.Error,
    onError = Color.White
)

/**
 * Dark color scheme for Chat - Primary theme
 */
val ChatDarkColorScheme = darkColorScheme(
    primary = ChatColors.Primary,
    onPrimary = Color.White,
    secondary = ChatColors.Accent,
    onSecondary = Color.White,
    tertiary = ChatColors.PrimaryLight,
    background = ChatColors.Background,
    onBackground = ChatColors.TextPrimary,
    surface = ChatColors.Surface,
    onSurface = ChatColors.TextPrimary,
    surfaceVariant = ChatColors.SurfaceVariant,
    onSurfaceVariant = ChatColors.TextSecondary,
    error = ChatColors.Error,
    onError = Color.White
)

/**
 * Premium Chat Typography - DM Sans style
 */
val ChatTypography = Typography(
    headlineMedium = TextStyle(
        fontWeight = FontWeight.Bold,
        fontSize = 24.sp,
        lineHeight = 32.sp,
        letterSpacing = (-0.5).sp
    ),
    titleLarge = TextStyle(
        fontWeight = FontWeight.SemiBold,
        fontSize = 20.sp,
        lineHeight = 28.sp,
        letterSpacing = (-0.3).sp
    ),
    titleMedium = TextStyle(
        fontWeight = FontWeight.SemiBold,
        fontSize = 16.sp,
        lineHeight = 24.sp
    ),
    bodyLarge = TextStyle(
        fontWeight = FontWeight.Normal,
        fontSize = 16.sp,
        lineHeight = 24.sp
    ),
    bodyMedium = TextStyle(
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 20.sp
    ),
    bodySmall = TextStyle(
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 16.sp
    ),
    labelLarge = TextStyle(
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.1.sp
    ),
    labelMedium = TextStyle(
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.3.sp
    ),
    labelSmall = TextStyle(
        fontWeight = FontWeight.Medium,
        fontSize = 10.sp,
        lineHeight = 14.sp,
        letterSpacing = 0.4.sp
    )
)

/**
 * Chat Shapes - Smooth rounded corners
 */
val ChatShapes = Shapes(
    small = RoundedCornerShape(8.dp),
    medium = RoundedCornerShape(12.dp),
    large = RoundedCornerShape(16.dp),
    extraLarge = RoundedCornerShape(24.dp)
)

/**
 * Premium Chat Theme composable - Always dark mode for AI-native look
 */
@Composable
fun ChatTheme(
    darkTheme: Boolean = true,  // Default to dark for AI-native aesthetic
    content: @Composable () -> Unit
) {
    val colorScheme = if (darkTheme) ChatDarkColorScheme else ChatLightColorScheme
    
    MaterialTheme(
        colorScheme = colorScheme,
        typography = ChatTypography,
        shapes = ChatShapes,
        content = content
    )
}
